'use strict';
function getSessions(){const m={};state.logs.forEach(l=>{m[l.sessionId]??={id:l.sessionId,date:l.date,workout:l.workout,exercises:0,volume:0};m[l.sessionId].exercises++;m[l.sessionId].volume+=l.sets.reduce((a,s)=>a+(s.weight*s.reps),0)});return Object.values(m).sort((a,b)=>new Date(b.date)-new Date(a.date))}
function updateDashboard(){const sessions=getSessions();document.getElementById('nextWorkout').textContent=state.next;document.getElementById('totalSessions').textContent=sessions.length;document.getElementById('totalSets').textContent=state.completedSets||0;document.getElementById('lastWorkout').textContent=sessions[0]?new Date(sessions[0].date).toLocaleDateString('tr-TR',{day:'2-digit',month:'short'}):'—';document.getElementById('prCount').textContent=getPRs().length;updateDataInsights()}
function getPRs(){const map={};state.logs.forEach(l=>l.sets.forEach(s=>{if(!s.weight||!s.reps)return;const e1=s.weight*(1+s.reps/30);if(!map[l.exercise]||e1>map[l.exercise].e1)map[l.exercise]={exercise:l.exercise,weight:s.weight,reps:s.reps,e1,date:l.date}}));return Object.values(map).sort((a,b)=>b.e1-a.e1)}
function updatePRBadges(){getPRs().forEach(p=>document.querySelectorAll(`[id="pr-A-${slug(p.exercise)}"],[id="pr-B-${slug(p.exercise)}"]`).forEach(el=>el.textContent=`PR: ${p.weight} kg × ${p.reps}`))}
function updateProgress(){const names=[...new Set([...programs.A.exercises,...programs.B.exercises].map(x=>x.name))];const sel=document.getElementById('chartExercise'),current=sel.value;sel.innerHTML=names.map(n=>`<option>${n}</option>`).join('');if(names.includes(current))sel.value=current;const prs=getPRs();document.getElementById('prList').innerHTML=prs.length?prs.map(p=>`<div class="set-grid" style="grid-template-columns:1.4fr .8fr .8fr .8fr"><b>${p.exercise}</b><span>${p.weight} kg</span><span>${p.reps} tekrar</span><span class="pr">e1RM ${p.e1.toFixed(1)}</span></div>`).join(''):'<div class="empty">Henüz PR kaydı yok.</div>';const sessions=getSessions();document.getElementById('historyList').innerHTML=sessions.length?`<div style="overflow:auto"><table class="history-table"><thead><tr><th>Tarih</th><th>Program</th><th>Hareket</th><th>En yüksek / hacim</th></tr></thead><tbody>${sessions.map(s=>{const logs=state.logs.filter(l=>l.sessionId===s.id),max=Math.max(0,...logs.map(l=>setMaxWeight(l.sets)));return `<tr><td>${new Date(s.date).toLocaleDateString('tr-TR')}</td><td>${s.workout}</td><td>${s.exercises}</td><td>${max?max.toLocaleString('tr-TR')+' kg':'—'}${s.volume?' / '+Math.round(s.volume).toLocaleString('tr-TR')+' kg':''}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">İlk antrenmanını kaydettiğinde burada görünecek.</div>';drawChart()}
function drawChart(){const canvas=document.getElementById('progressChart'),ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const name=document.getElementById('chartExercise').value,metric=document.getElementById('chartMetric').value;const rows=state.logs.filter(x=>x.exercise===name).sort((a,b)=>new Date(a.date)-new Date(b.date)).map(l=>{const maxW=Math.max(0,...l.sets.map(s=>s.weight));const vol=l.sets.reduce((a,s)=>a+s.weight*s.reps,0);const e1=Math.max(0,...l.sets.map(s=>s.weight*(1+s.reps/30)));return{date:l.date,value:metric==='weight'?maxW:metric==='volume'?vol:e1}});ctx.strokeStyle='#263042';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=25+i*(h-55)/4;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-15,y);ctx.stroke()}if(!rows.length){ctx.fillStyle='#9aa4b2';ctx.font='14px sans-serif';ctx.textAlign='center';ctx.fillText('Bu hareket için henüz kayıt yok.',w/2,h/2);return}const max=Math.max(...rows.map(r=>r.value),1),min=Math.min(...rows.map(r=>r.value),0),range=max-min||1;const pts=rows.map((r,i)=>({x:rows.length===1?w/2:45+i*(w-65)/(rows.length-1),y:25+(max-r.value)*(h-55)/range,...r}));ctx.strokeStyle='#6f91ff';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();pts.forEach(p=>{ctx.fillStyle='#8a6cff';ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#9aa4b2';ctx.font='11px sans-serif';ctx.textAlign='right';ctx.fillText(max.toFixed(metric==='volume'?0:1),36,30);ctx.fillText(min.toFixed(metric==='volume'?0:1),36,h-25)}
function updateDataInsights(){const box=document.getElementById('dataInsights');if(!box)return;const sessions=getSessions(),cutoff=Date.now()-30*86400000,recent=sessions.filter(x=>new Date(x.date).getTime()>=cutoff),recentLogs=state.logs.filter(x=>new Date(x.date).getTime()>=cutoff);const volume=recentLogs.reduce((a,l)=>a+l.sets.reduce((b,x)=>b+(Number(x.weight)||0)*(Number(x.reps)||0),0),0),counts={};recentLogs.forEach(l=>counts[l.exercise]=(counts[l.exercise]||0)+1);const favorite=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—',avg=(recent.length/(30/7)).toFixed(1).replace('.',',');box.innerHTML=`<div class="insight-card"><b>${recent.length}</b><span>Son 30 gün antrenman</span></div><div class="insight-card"><b>${Math.round(volume).toLocaleString('tr-TR')} kg</b><span>Son 30 gün toplam hacim</span></div><div class="insight-card"><b>${avg}</b><span>Haftalık ortalama</span></div><div class="insight-card"><b style="font-size:15px">${favorite}</b><span>En sık kaydedilen hareket</span></div>`}
function setMaxWeight(sets){return Math.max(0,...(sets||[]).map(x=>Number(x.weight)||0))}
function setVolume(sets){return (sets||[]).reduce((a,x)=>a+(Number(x.weight)||0)*(Number(x.reps)||0),0)}
function weightText(sets){const max=setMaxWeight(sets),vol=setVolume(sets);return max?`${max.toLocaleString('tr-TR')} kg${vol?` · ${Math.round(vol).toLocaleString('tr-TR')} hacim`:''}`:'Ağırlık girilmedi'}
function openStatDetails(type){
  const sessions=getSessions(),prs=getPRs(),modal=document.getElementById('statModal'),title=document.getElementById('statModalTitle'),body=document.getElementById('statModalBody');let html='';
  if(type==='sessions'){
    title.textContent='Tamamlanan Antrenmanlar';
    html=`<div class="stat-summary">${sessions.length}</div><div class="stat-list">${sessions.length?sessions.map(s=>{const logs=state.logs.filter(l=>l.sessionId===s.id),max=Math.max(0,...logs.map(l=>setMaxWeight(l.sets)));return `<div class="stat-row"><div><b>Antrenman ${s.workout}</b><small>${new Date(s.date).toLocaleDateString('tr-TR')}</small></div><span>${s.exercises} hareket</span><span>${max?max.toLocaleString('tr-TR')+' kg':'Ağırlık yok'}</span></div>`}).join(''):'<div class="empty">Henüz tamamlanan antrenman yok.</div>'}</div>`;
  }else if(type==='sets'){
    title.textContent='Tamamlanan Setler';const byEx={};
    state.logs.forEach(l=>l.sets.forEach(x=>{if(x.done){byEx[l.exercise]??={count:0,max:0,reps:0};byEx[l.exercise].count++;byEx[l.exercise].max=Math.max(byEx[l.exercise].max,Number(x.weight)||0);byEx[l.exercise].reps=Math.max(byEx[l.exercise].reps,Number(x.reps)||0)}}));
    html=`<div class="stat-summary">${state.completedSets||0}</div><div class="stat-list">${Object.keys(byEx).length?Object.entries(byEx).sort((a,b)=>b[1].count-a[1].count).map(([n,v])=>`<div class="stat-row"><b>${n}</b><span>${v.count} set</span><span>${v.max?v.max.toLocaleString('tr-TR')+' kg'+(v.reps?' × '+v.reps:''):'Ağırlık yok'}</span></div>`).join(''):'<div class="empty">Henüz tamamlanan set yok.</div>'}</div>`;
  }else if(type==='prs'){
    title.textContent='Kişisel Rekorlar';html=`<div class="stat-summary">${prs.length}</div><div class="stat-list">${prs.length?prs.map(p=>`<div class="stat-row"><b>${p.exercise}</b><span>${p.weight} kg × ${p.reps}</span><span class="pr">e1RM ${p.e1.toFixed(1)}</span></div>`).join(''):'<div class="empty">Henüz kişisel rekor yok.</div>'}</div>`;
  }else{
    title.textContent='Son Antrenman';const last=sessions[0];
    if(!last)html='<div class="empty">Henüz antrenman kaydı yok.</div>';
    else{const logs=state.logs.filter(l=>l.sessionId===last.id);html=`<div class="stat-summary">Antrenman ${last.workout}</div><div class="small" style="margin-bottom:12px">${new Date(last.date).toLocaleString('tr-TR')}</div><div class="stat-list">${logs.map(l=>`<div class="stat-row"><b>${l.exercise}</b><span>${l.sets.filter(x=>x.done).length}/${l.sets.length} set</span><span>${weightText(l.sets)}</span></div>`).join('')}</div>`}
  }
  body.innerHTML=html;modal.classList.add('show');document.body.style.overflow='hidden'
}
function closeStatDetails(){document.getElementById('statModal').classList.remove('show');document.body.style.overflow=''}
