'use strict';
function renderWorkout(code){const p=programs[code],root=document.getElementById('workout'+code);root.innerHTML=`<div class="section-title"><div><h3>${p.title}</h3><span>${p.subtitle}</span></div><button class="btn primary" onclick="finishWorkout('${code}')">Antrenmanı bitir</button></div>`+p.exercises.map((e,i)=>exerciseHTML(code,e,i)).join('');bindInputs(code)}
function exerciseHTML(code,e,i){const id=`${code}-${e.id||slug(e.name)}`;let rows='';for(let s=1;s<=e.sets;s++)rows+=`<div class="set-grid"><span class="set-no">Set ${s}</span><input class="field weight" type="number" min="0" step="0.5" placeholder="kg" data-id="${id}" data-set="${s}"><input class="field reps" type="number" min="0" placeholder="tekrar" data-id="${id}" data-set="${s}"><button class="check" data-id="${id}" data-set="${s}" onclick="toggleSet(this)">✓</button></div>`;return `<article class="exercise" data-exercise="${id}"><div class="exercise-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="exercise-title">${i+1}. ${e.name}</div><div class="exercise-sub">${e.sets} set • ${e.reps}</div><div class="badge-row"><span class="badge">Dinlenme: ${e.rest?e.rest+' sn':'—'}</span><span class="badge">${e.rir}</span><span class="badge pr" id="pr-${id}">PR: —</span></div></div><a class="video-link" href="${escapeAttr(e.video||('https://www.youtube.com/results?search_query='+encodeURIComponent(e.name+' proper form')))}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()">▶ YouTube</a></div><div class="exercise-body">${rows}<div class="note">${e.note}</div><div class="exercise-actions">${e.rest?`<button class="btn" onclick="startTimer(${e.rest})">⏱ ${e.rest} sn dinlen</button>`:''}<button class="btn good" onclick="saveExercise('${code}','${e.name.replace(/'/g,"\\'")}','${id}')">Hareketi kaydet</button></div></div></article>`}
function bindInputs(code){document.querySelectorAll(`#workout${code} input`).forEach(inp=>{const k=inp.dataset.id+'-'+inp.dataset.set+'-'+(inp.classList.contains('weight')?'w':'r');if(state.drafts[k]!=null)inp.value=state.drafts[k];inp.addEventListener('input',()=>{state.drafts[k]=inp.value;save()})});document.querySelectorAll(`#workout${code} .check`).forEach(b=>{const k='done-'+b.dataset.id+'-'+b.dataset.set;if(state.drafts[k])b.classList.add('done')});updatePRBadges()}
function toggleSet(btn){const k='done-'+btn.dataset.id+'-'+btn.dataset.set;state.drafts[k]=!state.drafts[k];btn.classList.toggle('done',state.drafts[k]);state.completedSets+=(state.drafts[k]?1:-1);if(state.completedSets<0)state.completedSets=0;save();updateDashboard();}
function collectExercise(id){return [...document.querySelectorAll(`[data-exercise="${id}"] .set-grid`)].map(r=>({weight:+(r.querySelector('.weight').value||0),reps:+(r.querySelector('.reps').value||0),done:r.querySelector('.check').classList.contains('done')})).filter(x=>x.weight||x.reps||x.done)}
function saveExercise(code,name,id){const sets=collectExercise(id);if(!sets.length)return toast('Önce en az bir set gir.');const today=new Date().toISOString();const existing=state.logs.find(x=>x.sessionId===currentSessionId(code)&&x.exercise===name);if(existing){existing.sets=sets;existing.date=today}else state.logs.push({sessionId:currentSessionId(code),workout:code,exercise:name,date:today,sets});save();updateDashboard();updateProgress();updatePRBadges();toast(name+' kaydedildi.');}
function currentSessionId(code){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}-${code}`}
function finishWorkout(code){programs[code].exercises.forEach(e=>{const id=`${code}-${e.id||slug(e.name)}`,sets=collectExercise(id);if(sets.length){const ex=state.logs.find(x=>x.sessionId===currentSessionId(code)&&x.exercise===e.name);if(ex){ex.sets=sets;ex.date=new Date().toISOString()}else state.logs.push({sessionId:currentSessionId(code),workout:code,exercise:e.name,date:new Date().toISOString(),sets})}});state.next=code==='A'?'B':'A';Object.keys(state.drafts).filter(k=>k.startsWith(code+'-')||k.startsWith('done-'+code+'-')).forEach(k=>delete state.drafts[k]);save();renderWorkout(code);updateDashboard();updateProgress();toast(`Antrenman ${code} tamamlandı. Sıradaki: ${state.next}`);if(getSessions().length%6===0)setTimeout(()=>confirm('6 antrenmandır yedek almadın. Şimdi JSON yedeği indirilsin mi?')&&exportData(),500)}
function startTimer(sec){stopTimer(false);timerEnd=Date.now()+sec*1000;tick();timerId=setInterval(tick,250)}function tick(){const left=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));document.getElementById('timerDisplay').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left<=0){stopTimer(false);toast('Dinlenme tamamlandı. Yeni set seni bekliyor.');if(navigator.vibrate)navigator.vibrate([200,100,200])}}function stopTimer(reset=true){clearInterval(timerId);timerId=null;if(reset)document.getElementById('timerDisplay').textContent='00:00'}
function openNextWorkout(){showPage('workout'+state.next)}function toggleNextWorkout(){state.next=state.next==='A'?'B':'A';save();updateDashboard();toast('Sıradaki antrenman '+state.next)}
// Son kayıttaki ağırlık ve tekrarları boş alanlara öneri olarak göster.
function applyLastSetHints(){
  document.querySelectorAll('.exercise').forEach(card=>{
    const title=card.querySelector('.exercise-title')?.textContent.replace(/^\d+\.\s*/, '');
    const rows=state.logs.filter(x=>x.exercise===title).sort((a,b)=>new Date(b.date)-new Date(a.date));
    if(!rows.length)return;
    const best=rows[0].sets.find(x=>x.weight||x.reps);
    if(!best)return;
    const sub=card.querySelector('.exercise-sub');
    if(sub && !card.querySelector('.last-set')) sub.insertAdjacentHTML('afterend',`<div class="last-set">Son kayıt: ${best.weight||0} kg × ${best.reps||0}</div>`);
  })
}
